[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Shashank Shadow.oncehuman@gmail.com"]
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.52.0",
    "python-telegram-bot>=22.5",
    "sift-stack-py>=0.9.1",
    "telegram>=0.0.1",
]
